//=include('vendors/swiper.min.js')
//=include('vendors/ScrollMagic.min.js')
//=include('vendors/lazyload.min.js')
//=include('vendors/isotope.pkgd.min.js')
//=include('vendors/isotope-packery.min.js')
//=include('vendors/barba.umd.js')
//=include('vendors/headroom.min.js')

//=include('vendors/feather.min.js')
//=include('vendors/jarallax.min.js')
//=include('vendors/popper.min.js')
//=include('vendors/nice-select2.js')

//=include('vendors/CustomEase.min.js')
//=include('vendors/gsap.min.js')
//=include('vendors/ScrollToPlugin.min.js')
//=include('vendors/SplitText.min.js')
//=include('vendors/DrawSVGPlugin.min.js')
//=include('vendors/glightbox.min.js')
